// <auto-generated />
// This file was generated by a R4Mvc.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the r4mvc.json file (i.e. the settings file), save it and rebuild.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo.Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

namespace Brewery.Web
{
    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public static partial class Links
    {
        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public static partial class css
        {
            public static string site_css = "~/css/site.css";
            public static string site_min_css = "~/css/site.min.css";
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public static partial class images
        {
            public static string banner1_svg = "~/images/banner1.svg";
            public static string banner2_svg = "~/images/banner2.svg";
            public static string banner3_svg = "~/images/banner3.svg";
            public static string banner4_svg = "~/images/banner4.svg";
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public static partial class js
        {
            public static string site_js = "~/js/site.js";
            public static string site_min_js = "~/js/site.min.js";
        }

        [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
        public static partial class lib
        {
            [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
            public static partial class bootstrap
            {
                [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                public static partial class dist
                {
                    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                    public static partial class css
                    {
                        public static string bootstrap_theme_css = "~/lib/bootstrap/dist/css/bootstrap-theme.css";
                        public static string bootstrap_theme_css_map = "~/lib/bootstrap/dist/css/bootstrap-theme.css.map";
                        public static string bootstrap_theme_min_css = "~/lib/bootstrap/dist/css/bootstrap-theme.min.css";
                        public static string bootstrap_theme_min_css_map = "~/lib/bootstrap/dist/css/bootstrap-theme.min.css.map";
                        public static string bootstrap_css = "~/lib/bootstrap/dist/css/bootstrap.css";
                        public static string bootstrap_css_map = "~/lib/bootstrap/dist/css/bootstrap.css.map";
                        public static string bootstrap_min_css = "~/lib/bootstrap/dist/css/bootstrap.min.css";
                        public static string bootstrap_min_css_map = "~/lib/bootstrap/dist/css/bootstrap.min.css.map";
                    }

                    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                    public static partial class fonts
                    {
                        public static string glyphicons_halflings_regular_eot = "~/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.eot";
                        public static string glyphicons_halflings_regular_svg = "~/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.svg";
                        public static string glyphicons_halflings_regular_ttf = "~/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf";
                        public static string glyphicons_halflings_regular_woff = "~/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff";
                        public static string glyphicons_halflings_regular_woff2 = "~/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2";
                    }

                    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                    public static partial class js
                    {
                        public static string bootstrap_js = "~/lib/bootstrap/dist/js/bootstrap.js";
                        public static string bootstrap_min_js = "~/lib/bootstrap/dist/js/bootstrap.min.js";
                        public static string npm_js = "~/lib/bootstrap/dist/js/npm.js";
                    }
                }

                public static string _bower_json = "~/lib/bootstrap/.bower.json";
                public static string LICENSE = "~/lib/bootstrap/LICENSE";
            }

            [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
            public static partial class jquery
            {
                [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                public static partial class dist
                {
                    public static string jquery_js = "~/lib/jquery/dist/jquery.js";
                    public static string jquery_min_js = "~/lib/jquery/dist/jquery.min.js";
                    public static string jquery_min_map = "~/lib/jquery/dist/jquery.min.map";
                }

                [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                public static partial class validation
                {
                    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                    public static partial class dist
                    {
                        public static string additional_methods_js = "~/lib/jquery-validation/dist/additional-methods.js";
                        public static string additional_methods_min_js = "~/lib/jquery-validation/dist/additional-methods.min.js";
                        public static string jquery_validate_js = "~/lib/jquery-validation/dist/jquery.validate.js";
                        public static string jquery_validate_min_js = "~/lib/jquery-validation/dist/jquery.validate.min.js";
                    }

                    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                    public static partial class unobtrusive
                    {
                        public static string _bower_json = "~/lib/jquery-validation-unobtrusive/.bower.json";
                        public static string jquery_validate_unobtrusive_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js";
                        public static string jquery_validate_unobtrusive_min_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js";
                    }

                    public static string _bower_json = "~/lib/jquery-validation/.bower.json";
                    public static string LICENSE_md = "~/lib/jquery-validation/LICENSE.md";
                }

                [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                public static partial class validation_unobtrusive
                {
                    public static string _bower_json = "~/lib/jquery-validation-unobtrusive/.bower.json";
                    public static string jquery_validate_unobtrusive_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js";
                    public static string jquery_validate_unobtrusive_min_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js";
                }

                public static string _bower_json = "~/lib/jquery/.bower.json";
                public static string LICENSE_txt = "~/lib/jquery/LICENSE.txt";
            }

            [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
            public static partial class jquery_validation
            {
                [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                public static partial class dist
                {
                    public static string additional_methods_js = "~/lib/jquery-validation/dist/additional-methods.js";
                    public static string additional_methods_min_js = "~/lib/jquery-validation/dist/additional-methods.min.js";
                    public static string jquery_validate_js = "~/lib/jquery-validation/dist/jquery.validate.js";
                    public static string jquery_validate_min_js = "~/lib/jquery-validation/dist/jquery.validate.min.js";
                }

                [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
                public static partial class unobtrusive
                {
                    public static string _bower_json = "~/lib/jquery-validation-unobtrusive/.bower.json";
                    public static string jquery_validate_unobtrusive_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js";
                    public static string jquery_validate_unobtrusive_min_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js";
                }

                public static string _bower_json = "~/lib/jquery-validation/.bower.json";
                public static string LICENSE_md = "~/lib/jquery-validation/LICENSE.md";
            }

            [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
            public static partial class jquery_validation_unobtrusive
            {
                public static string _bower_json = "~/lib/jquery-validation-unobtrusive/.bower.json";
                public static string jquery_validate_unobtrusive_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js";
                public static string jquery_validate_unobtrusive_min_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js";
            }
        }

        public static string favicon_ico = "~/favicon.ico";
    }

    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy()
        {
        }

        [GeneratedCode("R4Mvc", "1.0")]
        public static Dummy Instance = new Dummy();
    }

    public partial class BeweryAreaClass
    {
        public readonly Brewery.Web.Features.Bewery.Controllers.BeerController Beer = new Brewery.Web.Features.Bewery.Controllers.R4MVC_BeerController();
    }

    public partial class HomePageAreaClass
    {
        public readonly Brewery.Web.Features.HomePage.Controllers.HomePageController HomePage = new Brewery.Web.Features.HomePage.Controllers.R4MVC_HomePageController();
    }

    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public static partial class MVC
    {
        [GeneratedCode("R4Mvc", "1.0")]
        static readonly BeweryAreaClass s_Bewery = new BeweryAreaClass();
        [GeneratedCode("R4Mvc", "1.0")]
        public static BeweryAreaClass Bewery => s_Bewery;
        [GeneratedCode("R4Mvc", "1.0")]
        static readonly HomePageAreaClass s_HomePage = new HomePageAreaClass();
        [GeneratedCode("R4Mvc", "1.0")]
        public static HomePageAreaClass HomePage => s_HomePage;
        public static readonly Brewery.Web.Features.Shared.Controllers.BaseController Base = new Brewery.Web.Features.Shared.Controllers.R4MVC_BaseController();
    }

    internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult : ActionResult, IR4MvcActionResult
    {
        public R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(string area, string controller, string action, string protocol = null)
        {
            this.InitMVCT4Result(area, controller, action, protocol);
        }

        public string Controller
        {
            get;
            set;
        }

        public string Action
        {
            get;
            set;
        }

        public string Protocol
        {
            get;
            set;
        }

        public RouteValueDictionary RouteValueDictionary
        {
            get;
            set;
        }
    }

    internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_JsonResult : JsonResult, IR4MvcActionResult
    {
        public R4Mvc_Microsoft_AspNetCore_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base (null)
        {
            this.InitMVCT4Result(area, controller, action, protocol);
        }

        public string Controller
        {
            get;
            set;
        }

        public string Action
        {
            get;
            set;
        }

        public string Protocol
        {
            get;
            set;
        }

        public RouteValueDictionary RouteValueDictionary
        {
            get;
            set;
        }
    }
#pragma warning restore 1591, 3008, 3009, 0108
}